#
# MAINTAINER		midoks <midoks@163.com>
# DOCKER-VERSION 	17.12.0-ce, build c97c6d6
#
# Dockerizing Ubuntu: Dockerfile for building Ubuntu images


FROM 		midoks/centos:7.1
MAINTAINER  midoks <midoks@163.com>


RUN yum -y install etcd kubernetes