version: '2'

services:
  s1:
    image: 'tvial/docker-mailserver:latest'
    hostname: 'mail1'
    domainname: 'wangchenyu.net.cn'
    container_name: "mail"
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - './home/mail:/var/mail'
      - './home/mail-state:/var/mail-state'
      - './root/config/:/tmp/docker-mailserver/'
      - './etc/letsencrypt:/etc/letsencrypt'
    environment:
    - ENABLE_SPAMASSASSIN=0
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=letsencrypt
    cap_add:
    - NET_ADMIN